"""Scene construction (LED rig + occluders) from saved configuration files."""

from .absorbers import build_elios_absorbers, rotate_absorbers_z
from .builder import (
    Scene,
    apply_diffuser,
    apply_global_transform,
    build_leds_from_config,
    build_scene_from_config,
    build_scene_from_layout,
    group_config_to_factory,
    individual_led_config_to_factory,
    load_config,
)
from .layout import (
    SCHEMA_VERSION,
    Flux,
    Layout,
    LedSpec,
    Panel,
    Platform,
    StlModel,
    VioCameras,
    build_leds_from_layout,
    build_panel_leds,
    convert_v1,
    is_v2,
    layout_from_dict,
    load_layout,
    load_platform,
    save_json,
)
from .stl import global_z_rotation_4x4, stl_mesh_data, stl_transform

__all__ = [
    "SCHEMA_VERSION",
    "Flux",
    "Layout",
    "LedSpec",
    "Panel",
    "Platform",
    "Scene",
    "StlModel",
    "VioCameras",
    "apply_diffuser",
    "apply_global_transform",
    "build_elios_absorbers",
    "build_leds_from_config",
    "build_leds_from_layout",
    "build_panel_leds",
    "build_scene_from_config",
    "build_scene_from_layout",
    "convert_v1",
    "global_z_rotation_4x4",
    "group_config_to_factory",
    "individual_led_config_to_factory",
    "is_v2",
    "layout_from_dict",
    "load_config",
    "load_layout",
    "load_platform",
    "rotate_absorbers_z",
    "save_json",
    "stl_mesh_data",
    "stl_transform",
]
